# DATA SETTINGS
DEFAULT_TICKER = "AAPL"
DEFAULT_PERIOD = "6mo"
DEFAULT_INTERVAL = "1d"
DEFAULT_PRICE_COLUMN = "close"

# INDICATOR SETTINGS
SMA_PERIOD = 10
EMA_PERIOD = 20
RSI_PERIOD = 20

# STRATEGY SETTINGS
RSI_UPPER = 70
RSI_LOWER = 30

# SIMULATION SETTINGS
INITIAL_CASH = 10000
TRADE_QUANTITY = 1

# DISPLAY SETTINGS
DISPLAY_ROWS = 15

# PLOT SETTINGS
PLOT_FIGSIZE = (12, 6)
